<?php
// module/Cocktail/view/cocktail/cocktail/index.phtml:
$this->headScript()
        ->prependFile($this->basePath() . '/js/searchCocktail.js', 'text/javascript')
        ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js', 'text/javascript')
;

$title = 'Cocktails';
$this->headTitle($title);
?>

<!-- Block-->
<div class="container clients black">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="ui-widge row-fluid">
        <input id="tags" type="text" class="search-query span12 ui-autocomplete-input" autocomplete="off" placeholder="Search cocktail by name" />
        <br/>
        <br/>
    </div>
    <div id="cocktailList">
    <div class="row">
    <?php
    $count = 0;
    foreach ($cocktails as $cocktail) : ?>
        <?php
        if($count < 6)
        {
            $count++;
        }
        else
        {
            $count=0;
            print '</div><div class="row">';
        }
        ?>

            <div class="span2">
                <div class="thumbnail">
                    <a href="<?php echo $this->url('cocktail', array('action' => 'details', 'id' => $cocktail->idCocktail));?>">
                        <div class='hover-fader'><img src="<?php print BASE_URL; ?>/data/cocktailImages/<?php print $cocktail->cocktailImageAdress; ?>" alt="" style="height:200px"></div>
                        <div class="caption black">
                            <p><?php echo $this->escapeHtml($cocktail->cocktailName);?></p>
                        </div>
                    </a>
                </div>
            </div>

    <?php endforeach; ?>
    </div>
    </div>
    <br/>
    <button class="btn btn-success" id="request">Load more...</button>
</div>

